version: "3.8"
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: examplepassword
    ports:
      - "5432:5432"

  web:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://app_user:examplepassword@db:5432/app_db?schema=public"
      NODE_ENV: production
    ports:
      - "3000:3000"
